# Generated by Django 4.2.3 on 2023-08-11 07:55

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="compressed_file",
            field=models.FileField(
                blank=True, null=True, upload_to=files.models.compressed_upload_to
            ),
        ),
    ]
