# Generated by Django 4.2.3 on 2023-08-15 12:24

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_compressionrequested"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to=files.models.thumbnail_upload_to
            ),
        ),
        migrations.CreateModel(
            name="ThumbnailRequested",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail_requested",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
