# Generated by Django 4.2.3 on 2023-08-05 07:27

from django.db import migrations, models
import thalia.models


class Migration(migrations.Migration):
    dependencies = [
        ("thalia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticationrequest",
            name="challenge",
            field=models.CharField(
                default=thalia.models.get_random_challenge, max_length=80
            ),
        ),
    ]
