# Generated by Django 4.2.3 on 2023-08-05 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "get_latest_by": "-timestamp",
                "ordering": ["-timestamp"],
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
    ]
