# Generated by Django 4.2.3 on 2023-07-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
    ]
