# Generated by Django 4.2.3 on 2023-07-07 11:20

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=challenges.models.challenge_upload_image_to,
            ),
        ),
    ]
