# Generated by Django 4.2.3 on 2023-08-03 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("name", "tournament")},
        ),
    ]
