# Generated by Django 4.2.3 on 2023-08-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_transaction_options"),
        ("tournaments", "0002_rename_account_team_points_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="points_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="points_team",
                to="transactions.account",
            ),
        ),
    ]
