# Generated by Django 4.2.3 on 2023-08-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_alter_team_unique_together"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="tournaments.tournament",
            ),
        ),
    ]
