# Generated by Django 4.2.3 on 2023-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="submission_visibility",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Submissions are always visible"),
                    (
                        2,
                        "Submissions are visible when a team posted an accepted submission in the challenge",
                    ),
                ],
                default=1,
            ),
        ),
    ]
