# Generated by Django 4.2.3 on 2023-08-12 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenge_submission_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="transaction",
            new_name="points_transaction",
        ),
    ]
