# Generated by Django 4.2.3 on 2023-08-05 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_submission_tournament"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ("-created",)},
        ),
    ]
