# Generated by Django 4.2.3 on 2023-08-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_transaction_options"),
        ("challenges", "0003_rename_transaction_submission_points_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="coins_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coins_submission",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="points_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points_submission",
                to="transactions.transaction",
            ),
        ),
    ]
