---

name: "Build Production Docker Image (backend)"
on:
  push:
    branches:
      - master

jobs:
  build-docker-backend:
    name: "Build Docker Backend image"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./backend
    env:
      DOCKER_IMAGE: "docker.pkg.github.com/kioui/mentorpunten/mentorpunten-backend:latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v1"

      - name: "Login to GitHub Packages"
        run: "echo \"${{ secrets.GITHUB_TOKEN }}\" | docker login https://docker.pkg.github.com --username ${{ github.repository_owner }} --password-stdin"

      - name: "Build Docker image"
        run: "docker build --build-arg commit_hash=\"${{ github.sha }}\" --tag \"${DOCKER_IMAGE}\" ."

      - name: "Push Docker image"
        run: "docker push ${DOCKER_IMAGE}"


  build-docker-frontend:
    name: "Build Docker Frontend image"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./frontend
    env:
      DOCKER_IMAGE: "docker.pkg.github.com/kioui/mentorpunten/mentorpunten-frontend:latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v1"

      - name: "Login to GitHub Packages"
        run: "echo \"${{ secrets.GITHUB_TOKEN }}\" | docker login https://docker.pkg.github.com --username ${{ github.repository_owner }} --password-stdin"

      - name: "Build Docker image"
        run: "docker build --build-arg commit_hash=\"${{ github.sha }}\" --tag \"${DOCKER_IMAGE}\" ."

      - name: "Push Docker image"
        run: "docker push ${DOCKER_IMAGE}"
